module.exports = {
 // Main config
 author: "MrVenom",
 aurhor_website: "https://www.devmrvenom.ml/",
 owner_id: "607059199897108491",
 description: "",
 support_server: "https://discord.gg/bTY2quuXp3",
 status: "DND",
 twitter: "https://twitter.com/mrToxic_007",
 github: "https://www.github.com/venom-hun5",
 github_repo: "",
 about_bot: "... Soon!",
 about_dev: "... Soon!",
 donation_perks: "",
 patreon: "https://www.patreon.com/DevVenom/",
 ko_fi: "",
 buymeacoffee: "",
 open_collective: "",
 scopes: "bot%20applications.commands",
 permissions: "8",
 suggestions_channel: "",
 bot_news_title: "",
 news: "Bolt V2",
 brainid: process.env.BRAINID,
 brainkey: process.env.BRAINKEY,
 prefix: process.env.PREFIX,
 youtube: process.env.YOUTUBE,
 id: process.env.ID,
 advanved_logging: false,

 // Dashboard config
 domain: process.env.DOMAIN,
 certs: false,
 localhost: false,
 privacy_policy_page: true,
 google_analitics: process.env.ANALYTICS,
 client_secret: process.env.SECRET,
 port: process.env.PORT,
 session_secret: process.env.SESSION_SECRET,
 dashboard: process.env.DASHBOARD,
 cookies: process.env.COOKIES,
 mobile_support: "false",
 image: "banner.jpg",
 verification: "-wuCsk4qLolXEPSUTGX7YBxywcyNNf5HS2ClzgEWxNY",
};
